# Generated by `rjournal_pdf_article()` using `knitr::purl()`: do not edit by hand
# Please edit datadriftR.Rmd to modify this file

## ----setup, include=FALSE-----------------------------------------------------
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(plotly)
library(ggplot2)
library(palmerpenguins)
library(kableExtra)
knitr::opts_chunk$set(fig.pos = 'H',fig.align='center')


## ----mdp, out.width = "80%", out.height = "20%", fig.cap = "The predictive modeling process"----
knitr::include_graphics("figures/mdp_resize.png")


## ----pdd, out.width = "80%", out.height = "20%", fig.cap = "The workflow of the Profile Drift Detection"----
knitr::include_graphics("figures/pdd_resize.png")


## ----sealogistic, out.width = "95%", fig.cap = "PDPs of the Logistic Regression model trained on \\texttt{SEA} dataset"----
knitr::include_graphics("figures/sea_logistic_10.png")


## ----seadecisiontree, out.width = "95%", fig.cap = "PDPs of the Decision Tree model trained on \\texttt{SEA} dataset"----
knitr::include_graphics("figures/sea_dt_10.png")


## ----searandomforest, out.width = "95%", fig.cap = "PDPs of the Random Forest model trained on \\texttt{SEA} dataset"----
knitr::include_graphics("figures/sea_rf_10.png")


## ----rfelec10, out.width = "80%", fig.cap = "PDPs of the Random Forest model trained on \\texttt{Elec2} dataset"----
knitr::include_graphics("figures/rf_elec_10.png")

